import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['icon.svg', 'favicon.ico', 'apple-touch-icon-180x180.png'],
      manifest: {
        name: 'Cookbook',
        short_name: 'Cookbook',
        description: 'Follow chefs, build your cookbook, cook from your fridge.',
        theme_color: '#D9542B',
        background_color: '#F8F7F5',
        display: 'standalone',
        start_url: '/',
        // Generated by `npx pwa-assets-generator` from public/icon.svg - rerun
        // that if the source icon changes, rather than editing these by hand.
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          { src: 'maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
    }),
  ],
  server: {
    // Pinned rather than left to Vite's default (5173): another project on
    // this machine (C:\Users\bjenn\CookBook\apps\web) also defaults to 5173,
    // and whichever dev server starts last silently steals the port.
    port: 5180,
    strictPort: true,
    proxy: {
      '/api': {
        target: 'http://localhost:8090',
        changeOrigin: true,
      },
    },
  },
})
