-- Editing, with an audit trail.
--
-- Two rules borrowed from the HoopWiki spec, because they're the difference
-- between a wiki you can trust and one you can't:
--   * nothing is ever hard-deleted - a removed meal goes to status='deleted'
--   * every edit writes a revision row; a body is never silently overwritten
-- Without these, a bad edit (or a bad actor) is unrecoverable and invisible.

ALTER TABLE meals ADD COLUMN status TEXT NOT NULL DEFAULT 'live'
    CHECK (status IN ('live','deleted'));
ALTER TABLE meals ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

-- Partial index: every listing query filters to live meals, and deleted ones
-- should never cost anything to skip.
CREATE INDEX meals_live_idx ON meals(id) WHERE status = 'live';

-- A full snapshot of the meal *before* each change, so any revision can be
-- restored whole rather than reconstructed from diffs. JSONB rather than a
-- shadow table because the shape is denormalised on purpose - it must keep
-- working even if the current schema moves on.
CREATE TABLE meal_revisions (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    meal_id    BIGINT NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
    editor_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
    -- Denormalised so history survives an account deletion with attribution.
    editor_name TEXT,
    snapshot   JSONB NOT NULL,
    -- Human-readable summary of what changed, generated by diffing.
    summary    TEXT NOT NULL DEFAULT '',
    kind       TEXT NOT NULL DEFAULT 'edit'
        CHECK (kind IN ('created','edit','revert','deleted','restored')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX meal_revisions_meal_idx ON meal_revisions(meal_id, created_at DESC);

-- Voting on edits, not just on food. One vote per person per revision - the
-- composite PK *is* that guarantee, so no surrogate id here.
-- Cooks who've actually made the dish are the people worth hearing from about
-- whether a change improved it, which is why `cooked` is recorded at cast time.
CREATE TABLE revision_votes (
    revision_id BIGINT NOT NULL REFERENCES meal_revisions(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- +1 improvement, -1 regression. No zero: abstaining is just not voting.
    value       SMALLINT NOT NULL CHECK (value IN (-1, 1)),
    -- Whether the voter had cooked this meal when they voted. Frozen at cast
    -- time so later cooking can't retroactively re-weight an old vote.
    cooked      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (revision_id, user_id)
);
CREATE INDEX revision_votes_revision_idx ON revision_votes(revision_id);

-- Which version of the recipe a review was actually written against. A five
-- star review of a recipe that has since been rewritten is not a review of the
-- current recipe, and the page should be able to say so.
ALTER TABLE reviews ADD COLUMN meal_revision_count INTEGER NOT NULL DEFAULT 0;

-- Reverts are the strongest quality signal a recipe emits: a page that keeps
-- getting rolled back is unstable, and stability feeds ranking in iteration 3.
ALTER TABLE meals ADD COLUMN revert_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE meals ADD COLUMN last_reverted_at TIMESTAMPTZ;
